# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    env:
      working-directory: ./client 
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1 
    - run: msbuild game-overlay/gameoverlay.sln
      working-directory: ./
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm link ../electron-overlay
      working-directory: ${{env.working-directory}}
    - run: npm link ../node-ovhook
      working-directory: ${{env.working-directory}}
    - run: npm i
      working-directory: ${{env.working-directory}}
    - run: npm run compile:electron
      working-directory: ${{env.working-directory}}
    - run: npm run build
      working-directory: ${{env.working-directory}}
